# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study05', '0003_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30, verbose_name='标题')),
                ('content_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study05.Movies', verbose_name='集数')),
            ],
        ),
    ]
