# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hyrz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='c_name', max_length=40, verbose_name='分类名')),
                ('desc', models.TextField(max_length=1000, verbose_name='描述')),
            ],
        ),
    ]
