# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study02', '0003_auto_20180710_1124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hyrz',
            table='category',
        ),
    ]
