# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study02', '0004_auto_20180710_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyrz',
            name='name',
            field=models.CharField(db_column='c_name', max_length=40, unique=True, verbose_name='分类名'),
        ),
    ]
