# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study02', '0006_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('authors', models.ManyToManyField(to='study02.Author')),
            ],
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=18, verbose_name='身份证号')),
                ('unite', models.CharField(max_length=30, verbose_name='签发单位')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('idcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study02.IdCard', verbose_name='身份证')),
            ],
        ),
    ]
