# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-17 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study07', '0002_auto_20180717_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='游戏角色')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study07.Player', verbose_name='所属游戏')),
            ],
        ),
    ]
