# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='卡号')),
                ('bank_name', models.CharField(max_length=30, verbose_name='银行名字')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='人名')),
                ('age', models.IntegerField()),
                ('bankcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study04.BankCard', verbose_name='银行卡')),
            ],
        ),
    ]
