# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study04', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('life', models.IntegerField(verbose_name='职业生涯')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='语言名字')),
                ('desc', models.CharField(max_length=255, verbose_name='描述')),
            ],
        ),
        migrations.AddField(
            model_name='engineer',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study04.Language', verbose_name='掌握的语言'),
        ),
    ]
