# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=10, verbose_name='班级名称')),
                ('gdate', models.DateTimeField(verbose_name='开班日期')),
                ('ggirlnum', models.IntegerField(verbose_name='女生数量')),
                ('gboynum', models.IntegerField(verbose_name='男生数量')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否已逻辑删除该班级')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('sgender', models.BooleanField(default=True, verbose_name='学生性别')),
                ('sage', models.IntegerField(verbose_name='学生年龄')),
                ('sinfo', models.CharField(max_length=20, verbose_name='备注信息')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除学生')),
                ('sgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Grade')),
            ],
        ),
    ]
